bot:
  name: ChemistALT_bot
  token: 6214620768:AAGHNTVP8HNa1nvoqtjvyZh-OJdxoHOiT8w
crone:
  scheduler: 0 0 1 * * *

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/chemical-bot
    username: postgres
    password: postgres
